//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAPServicesTest.UsuariosWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/SOAPServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOAPServicesTest.UsuariosWS.Rol RolField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOAPServicesTest.UsuariosWS.Rol Rol {
            get {
                return this.RolField;
            }
            set {
                if ((object.ReferenceEquals(this.RolField, value) != true)) {
                    this.RolField = value;
                    this.RaisePropertyChanged("Rol");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rol", Namespace="http://schemas.datacontract.org/2004/07/SOAPServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Rol : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsuariosWS.IUsuarios")]
    public interface IUsuarios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/CrearUsuario", ReplyAction="http://tempuri.org/IUsuarios/CrearUsuarioResponse")]
        SOAPServicesTest.UsuariosWS.Usuario CrearUsuario(string nombre, string correo, int rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/CrearUsuario", ReplyAction="http://tempuri.org/IUsuarios/CrearUsuarioResponse")]
        System.Threading.Tasks.Task<SOAPServicesTest.UsuariosWS.Usuario> CrearUsuarioAsync(string nombre, string correo, int rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/ObtenerUsuario", ReplyAction="http://tempuri.org/IUsuarios/ObtenerUsuarioResponse")]
        SOAPServicesTest.UsuariosWS.Usuario ObtenerUsuario(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/ObtenerUsuario", ReplyAction="http://tempuri.org/IUsuarios/ObtenerUsuarioResponse")]
        System.Threading.Tasks.Task<SOAPServicesTest.UsuariosWS.Usuario> ObtenerUsuarioAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/ModificarUsuario", ReplyAction="http://tempuri.org/IUsuarios/ModificarUsuarioResponse")]
        SOAPServicesTest.UsuariosWS.Usuario ModificarUsuario(int codigo, string nombre, string correo, int rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/ModificarUsuario", ReplyAction="http://tempuri.org/IUsuarios/ModificarUsuarioResponse")]
        System.Threading.Tasks.Task<SOAPServicesTest.UsuariosWS.Usuario> ModificarUsuarioAsync(int codigo, string nombre, string correo, int rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/EliminarUsuario", ReplyAction="http://tempuri.org/IUsuarios/EliminarUsuarioResponse")]
        void EliminarUsuario(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/EliminarUsuario", ReplyAction="http://tempuri.org/IUsuarios/EliminarUsuarioResponse")]
        System.Threading.Tasks.Task EliminarUsuarioAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/ListarUsuarios", ReplyAction="http://tempuri.org/IUsuarios/ListarUsuariosResponse")]
        SOAPServicesTest.UsuariosWS.Usuario[] ListarUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/ListarUsuarios", ReplyAction="http://tempuri.org/IUsuarios/ListarUsuariosResponse")]
        System.Threading.Tasks.Task<SOAPServicesTest.UsuariosWS.Usuario[]> ListarUsuariosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuariosChannel : SOAPServicesTest.UsuariosWS.IUsuarios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuariosClient : System.ServiceModel.ClientBase<SOAPServicesTest.UsuariosWS.IUsuarios>, SOAPServicesTest.UsuariosWS.IUsuarios {
        
        public UsuariosClient() {
        }
        
        public UsuariosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuariosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuariosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuariosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SOAPServicesTest.UsuariosWS.Usuario CrearUsuario(string nombre, string correo, int rol) {
            return base.Channel.CrearUsuario(nombre, correo, rol);
        }
        
        public System.Threading.Tasks.Task<SOAPServicesTest.UsuariosWS.Usuario> CrearUsuarioAsync(string nombre, string correo, int rol) {
            return base.Channel.CrearUsuarioAsync(nombre, correo, rol);
        }
        
        public SOAPServicesTest.UsuariosWS.Usuario ObtenerUsuario(int codigo) {
            return base.Channel.ObtenerUsuario(codigo);
        }
        
        public System.Threading.Tasks.Task<SOAPServicesTest.UsuariosWS.Usuario> ObtenerUsuarioAsync(int codigo) {
            return base.Channel.ObtenerUsuarioAsync(codigo);
        }
        
        public SOAPServicesTest.UsuariosWS.Usuario ModificarUsuario(int codigo, string nombre, string correo, int rol) {
            return base.Channel.ModificarUsuario(codigo, nombre, correo, rol);
        }
        
        public System.Threading.Tasks.Task<SOAPServicesTest.UsuariosWS.Usuario> ModificarUsuarioAsync(int codigo, string nombre, string correo, int rol) {
            return base.Channel.ModificarUsuarioAsync(codigo, nombre, correo, rol);
        }
        
        public void EliminarUsuario(int codigo) {
            base.Channel.EliminarUsuario(codigo);
        }
        
        public System.Threading.Tasks.Task EliminarUsuarioAsync(int codigo) {
            return base.Channel.EliminarUsuarioAsync(codigo);
        }
        
        public SOAPServicesTest.UsuariosWS.Usuario[] ListarUsuarios() {
            return base.Channel.ListarUsuarios();
        }
        
        public System.Threading.Tasks.Task<SOAPServicesTest.UsuariosWS.Usuario[]> ListarUsuariosAsync() {
            return base.Channel.ListarUsuariosAsync();
        }

        internal int ObtenerUsuario(string p)
        {
            throw new NotImplementedException();
        }

        internal int ObtenerUsuario(int p1, int p2)
        {
            throw new NotImplementedException();
        }
    }
}
